'''
Problem 44.

Pentagonal numbers are generated by the formula, P(n) = n(3*n - 1)/2. The first
ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P(4) + P(7) = 22 + 70 = 92 = P(8). However, their
difference, 70  22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, P(m) and P(k), for which their sum and
difference is pentagonal and D = |P(k) - P(m)| is minimised; what is the value
of D?

@author: Curtis Belmonte
'''
from common import is_pentagonal, pentagonal_num

diff = -1
k = 0
while not is_pentagonal(diff):
    k += 1
    for m in range(k, 0, -1):
        if is_pentagonal(pentagonal_num(m) + pentagonal_num(k)):
            diff = pentagonal_num(k) - pentagonal_num(m)
print(diff)