"""problem_044.py

Problem 44: Pentagon numbers

Pentagonal numbers are generated by the formula, P(n) = n(3*n - 1)/2. The first
ten pentagonal numbers are:

    1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P(4) + P(7) = 22 + 70 = 92 = P(8). However, their
difference, 70 - 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, P(m) and P(k), for which their sum and
difference is pentagonal and D = |P(k) - P(m)| is minimised; what is the value
of D?

@author: Curtis Belmonte
"""

import common

# PARAMETERS ##################################################################

# N/A

# SOLUTION ####################################################################

diff = -1
k = 0
while not common.is_pentagon_number(diff):
    k += 1
    p_k = common.pentagon_number(k)
    for m in range(k, 0, -1):
        p_m = common.pentagon_number(m)
        if common.is_pentagon_number(p_m + p_k):
            diff = p_k - p_m
print(diff)