/*
 * problem002.cpp
 * 
 * Problem 2: Even Fibonacci numbers
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 *     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not
 * exceed LIMIT, find the sum of the even-valued terms.
 * 
 * Author: Curtis Belmonte
 * Created: Aug 19, 2014
 */

#include <iostream>

#include "common.h"

using namespace std;

/* PARAMETERS *****************************************************************/

static int LIMIT = 4000000; // default: 4000000

/* FUNCTIONS ******************************************************************/

// None

/* SOLUTION *******************************************************************/

int main() {
    int i = -1;
    int f = 0;
    int sum = 0;
    while (f <= LIMIT) {
        sum += f;
        i += 3;
        f = common::fibonacci(i);
    }
    cout << sum << endl;
    return 0;
}
