/*
 * problem012.cpp
 *
 * Problem 12: Highly divisible triangular number
 *
 * The sequence of triangle numbers is generated by adding the natural numbers.
 * So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The
 * first ten terms would be:
 *
 *     1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 *
 * Let us list the factors of the first seven triangle numbers:
 *
 *      1: 1
 *      3: 1, 3
 *      6: 1, 2, 3, 6
 *     10: 1, 2, 5, 10
 *     15: 1, 3, 5, 15
 *     21: 1, 3, 7, 21
 *     28: 1, 2, 4, 7, 14, 28
 *
 * We can see that 28 is the first triangle number to have over five divisors.
 * 
 * What is the value of the first triangle number to have over N divisors?
 * 
 * Author: Curtis Belmonte
 * Created: Aug 25, 2014
 */

#include <iostream>

#include "common.h"

using namespace std;

/* PARAMETERS ****************************************************************/

static const unsigned int N = 500; // default: 500

/* SOLUTION ******************************************************************/

/* Returns the number of divisors of the triangle number n*(n + 1)/2. */
inline static common::Natural countTriangleDivisors(common::Natural n) {
    // because n and n + 1 are necessarily coprime, sum their divisor counts
    if (n % 2 == 0)
        // n component of triangle number is evenly divisible by 2
        return common::countDivisors(n / 2) * common::countDivisors(n + 1);
    else
        // n + 1 component of triangle number is evenly divisible by 2
        return common::countDivisors(n) * common::countDivisors((n + 1) / 2);
}

int main() {
    common::Natural n = 1;
    while (countTriangleDivisors(n) < N)
        n++;

    cout << n * (n + 1) / 2 << endl;
    return 0;
}
